name: Test, lint, verify modules
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests, run linter, verify Node modules
      run: yarn run ci-install-and-verify
