name: Test, lint, verify modules
on: [ "pull_request", "push" ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read NodeJS version form .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvmrc

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{steps.nvmrc.outputs.NVMRC}}
        cache: 'yarn'

    - name: Run tests, run linter, verify Node modules
      run: yarn run ci-install-and-verify
