name: Test, lint, verify modules
on: [ "pull_request", "push" ]
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.ci-verifier.yml
# TODO:      DOCKER_USER: ${{ secrets.DOCKER_USER }}
# TODO:      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
    - name: Code checkout
    - uses: actions/checkout@v2

    - name: Build image with tests
      run: docker compose build

    - name: Run tests, run linter, verify Node modules
      run: docker-compose.ci-verifier.yml run ci-verifier
